services:
  db:
    image: postgres:16
    container_name: privet_db

    environment:
      POSTGRES_DB: privet
      POSTGRES_USER: privet
      POSTGRES_PASSWORD: privet

    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - privet_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U privet -d privet"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  privet_postgres_data: