# Generated by Django 5.2.17 on 2026-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('redeemed', 'Redeemed'), ('disabled', 'Disabled')], default='available', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invitecode',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['available', 'redeemed', 'disabled'])), name='ck_invite_status'),
        ),
        migrations.AddConstraint(
            model_name='invitecode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('redeemed_at__isnull', False), ('redeemed_by_user__isnull', False), ('status', 'redeemed')), models.Q(models.Q(('status', 'redeemed'), _negated=True), ('redeemed_at__isnull', True), ('redeemed_by_user__isnull', True)), _connector='OR'), name='ck_invite_redeemed_state'),
        ),
    ]
