# Generated by Django 5.2.17 on 2026-10-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=128, unique=True)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('fill_blank', 'Fill blank'), ('fill_choice', 'Fill choice'), ('contextual', 'Contextual')], max_length=32)),
                ('question_text', models.TextField()),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], max_length=2)),
                ('is_extension', models.BooleanField(default=False)),
                ('difficulty_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('accepted_answers', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'question',
                'constraints': [models.CheckConstraint(condition=models.Q(('difficulty_score__gte', 0), ('difficulty_score__lte', 1)), name='ck_question_difficulty'), models.CheckConstraint(condition=models.Q(('cefr_level__in', ('A1', 'A2', 'B1'))), name='ck_question_cefr'), models.CheckConstraint(condition=models.Q(('question_type__in', ('multiple_choice', 'fill_blank', 'fill_choice', 'contextual'))), name='ck_question_type')],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('option_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionbank.question')),
            ],
            options={
                'db_table': 'question_option',
                'ordering': ('question', 'display_order', 'option_id'),
                'indexes': [models.Index(fields=['question', 'display_order'], name='idx_qopt_question_order')],
                'constraints': [models.UniqueConstraint(fields=('option_id', 'question'), name='uq_option_question_pair')],
            },
        ),
        migrations.CreateModel(
            name='QuestionSkill',
            fields=[
                ('question_skill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=6)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_skills', to='questionbank.question')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_skills', to='curriculum.skill')),
            ],
            options={
                'db_table': 'question_skill',
                'indexes': [models.Index(fields=['skill', 'question'], name='idx_qs_skill_question')],
                'constraints': [models.UniqueConstraint(fields=('question', 'skill'), name='uq_question_skill_pair'), models.CheckConstraint(condition=models.Q(('weight__gt', 0), ('weight__lte', 1)), name='ck_qs_weight'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('question',), name='uq_qs_primary')],
            },
        ),
    ]
