# Generated by Django 5.2.17 on 2026-10-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_add_question_skill_integrity_triggers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionskill',
            name='uq_qs_primary',
        ),
    ]
