# Generated by Django 5.2.17 on 2026-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0003_remove_questionskill_uq_qs_primary'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_answers__isnull', True), ('accepted_answers__contains', []), _connector='OR'), name='ck_question_accepted_answers_array'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='uq_qopt_one_correct'),
        ),
    ]
