# Generated by Django 5.2.17 on 2026-10-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0004_question_ck_question_accepted_answers_array_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionoption',
            name='uq_qopt_one_correct',
        ),
    ]
