# Generated by Django 5.2.17 on 2026-10-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'topic',
                'ordering': ('display_order', 'topic_id'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], max_length=2)),
                ('is_extension', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='curriculum.topic')),
            ],
            options={
                'db_table': 'skill',
                'ordering': ('topic', 'display_order', 'skill_id'),
                'constraints': [models.UniqueConstraint(fields=('topic', 'skill_name'), name='uq_skill_topic_name')],
            },
        ),
    ]
