# Generated by Django 5.2.17 on 2026-10-05 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(max_length=32)),
                ('content', models.JSONField()),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lesson',
                'ordering': ('display_order', 'lesson_id'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'topic',
                'ordering': ('display_order', 'topic_id'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], max_length=2)),
                ('is_extension', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='curriculum.topic')),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('lesson_progress_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=16)),
                ('completion_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='curriculum.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_progress',
                'indexes': [models.Index(fields=['user', '-last_accessed_at'], name='idx_lp_user_recent')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='uq_lesson_progress_user_lesson'), models.CheckConstraint(condition=models.Q(('completion_ratio__gte', 0), ('completion_ratio__lte', 1)), name='ck_lesson_progress_completion_ratio'), models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'completed'])), name='ck_lesson_progress_status'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='ck_lesson_progress_completed_state')],
            },
        ),
        migrations.CreateModel(
            name='LessonSkill',
            fields=[
                ('lesson_skill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_skills', to='curriculum.lesson')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_skills', to='curriculum.skill')),
            ],
            options={
                'db_table': 'lesson_skill',
                'indexes': [models.Index(fields=['skill', 'lesson'], name='idx_lesson_skill_skill')],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'skill'), name='uq_lesson_skill_pair')],
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('topic', 'skill_name'), name='uq_skill_topic_name'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.CheckConstraint(condition=models.Q(('cefr_level__in', ['A1', 'A2', 'B1'])), name='ck_skill_cefr'),
        ),
    ]
