# Generated by Django 5.2.17 on 2026-10-05 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_lesson_lessonprogress_lessonskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterField(
            model_name='lessonskill',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_skills', to='curriculum.lesson'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'completed'])), name='ck_lesson_progress_status'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='ck_lesson_progress_completed_state'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.CheckConstraint(condition=models.Q(('cefr_level__in', ['A1', 'A2', 'B1'])), name='ck_skill_cefr'),
        ),
    ]
